---
services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entryPoint=web
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.myresolver.acme.email=me@diegordonez.com
    ports:
      - 443:443
      - 80:80
      - 8080:8080
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
  
  whoami:
    image: traefik/whoami
    container_name: test-services
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`trf01.monojaus.com`)"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"