services:
  dms:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mta.monojaus.com
    depends_on: 
      - reverse-proxy
    environment:
      - TZ=Europe/Madrid
      - SSL_TYPE=letsencrypt
      - SSL_DOMAIN=mta.monojaus.com
      - TLS_LEVEL=intermediate
    labels:
      - traefik.enable=true
      # Explicit TLS (STARTTLS):
      - traefik.tcp.routers.mail-smtp.rule=HostSNI(`*`)
      - traefik.tcp.routers.mail-smtp.entrypoints=mail-smtp
      - traefik.tcp.routers.mail-smtp.service=mail-smtp
      - traefik.tcp.services.mail-smtp.loadbalancer.server.port=25
      - traefik.tcp.services.mail-smtp.loadbalancer.proxyProtocol.version=2

      # Implicit TLS is no different, except for optional HostSNI support:
      - traefik.tcp.routers.mail-submissions.rule=HostSNI(`mta.monojaus.com`)
      - traefik.tcp.routers.mail-submissions.tls.passthrough=true
      - traefik.tcp.routers.mail-submissions.entrypoints=mail-submissions
      - traefik.tcp.routers.mail-submissions.service=mail-submissions
      - traefik.tcp.services.mail-submissions.loadbalancer.server.port=465
      - traefik.tcp.services.mail-submissions.loadbalancer.proxyProtocol.version=2
    volumes:
      - ./dms/mail-data/:/var/mail/
      - ./dms/mail-state/:/var/mail-state/
      - ./dms/mail-logs/:/var/log/mail/
      - ./dms/config/:/tmp/docker-mailserver/
      - ./letsencrypt/acme.json:/etc/letsencrypt/acme.json:ro
      - /etc/localtime:/etc/localtime:ro

  reverse-proxy:
    image: docker.io/traefik:latest
    container_name: traefik
    command:
      - --api.insecure=true
      - --entryPoints.web.address=:80
      # SSL/TLS certs config
      - --entryPoints.websecure.address=:443
      # Docker provider config:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # DMS ports you want to proxy:
      - --entryPoints.mail-smtp.address=:25
      # Explicit TLS - legacy compatibility
      - --entryPoints.mail-submission.address=:587
      # Implicit TLS - Preferred
      - --entryPoints.mail-submissions.address=:465
      - --entryPoints.mail-imap.address=:143
      - --entryPoints.mail-imaps.address=:993
      - --entryPoints.mail-pop3.address=:110
      - --entryPoints.mail-pop3s.address=:995
      - --entryPoints.mail-managesieve.address=:4190
      # Ending mailserver definition
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entryPoint=web
      - --certificatesresolvers.letsencrypt.acme.storage=/acme.json
      - --certificatesresolvers.letsencrypt.acme.email=me@diegordonez.com
    # Publish external access ports mapped to traefik entrypoint ports:
    ports:
      #traefik dashboard
      - "443:443"
      - "80:80"
      - "8080:8080"
      #DMS
      - "25:25"
      - "587:587"
      - "465:465"
      - "143:143"
      - "993:993"
      - "110:110"
      - "995:995"
      - "4190:4190"
    # An IP is assigned here for other services (Dovecot) to trust for PROXY protocol:
    networks:
      default:
        ipv4_address: 172.16.42.2
    volumes:
      - ./letsencrypt/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  default:
    name: traefik-net
    ipam:
      config:
        - subnet: "172.16.42.0/24" # It will always set the same CIDR range