services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mta.monojaus.com
    restart: always
    labels:
      - traefik.enable=true #Indicates traefik is a routable host
      - traefik.tcp.routers.smtp.rule=HostSNI(`*`) #Listening point for SMTP communication
      - traefik.tcp.routers.smtp.service=smtp # Gets entrypoint created at traefik (main rp)
      - traefik.tcp.services.smtp.loadbalancer.server.port=25
      - traefik.tcp.services.smtp.loadbalancer.proxyProtocol.version=1
      # Labels below defines SSL configuration for mailserver
      - traefik.tcp.routers.smtp-ssl.rule=HostSNI(`*`) #Listening point for SMTP communication over TLS
      - traefik.tcp.routers.smtp-ssl.tls.passthrough=true #SSL termination disabled
      - traefik.tcp.routers.smtp-ssl.service=smtp-ssl
      - traefik.tcp.services.smtp-ssl.loadbalancer.server.port=465 # It defines secure port for TLS
      - traefik.tcp.services.smtp-ssl.loadbalancer.proxyProtocol.version=1
      # The following labels applies to IMAP and Sieve services, but it's intended to be disabled
      - traefik.tcp.services.imap-ssl.loadbalancer.proxyProtocol.version=2
      - traefik.tcp.routers.imap-ssl.rule=HostSNI(`*`)
      - traefik.tcp.routers.sieve.entrypoints=sieve
      - traefik.tcp.routers.imap-ssl.entrypoints=imap-ssl
      - traefik.tcp.services.sieve.loadbalancer.server.port=4190
      - traefik.tcp.routers.imap-ssl.service=imap-ssl
      - traefik.tcp.routers.imap-ssl.tls.passthrough=true
      - traefik.tcp.services.imap-ssl.loadbalancer.server.port=10993
      - traefik.tcp.routers.sieve.rule=HostSNI(`*`)
      - traefik.tcp.routers.sieve.service=sieve
    environment:
      - ENABLE_RSPAMD=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - SSL_TYPE=letsencrypt
      - SSL_DOMAIN=mta.monojaus.com
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    expose:
      - "25"
      - "465"
      - "587"
      - "993"
    volumes:
      - ./dms/mail-data/:/var/mail/
      - ./dms/mail-state/:/var/mail-state/
      - ./dms/mail-logs/:/var/log/mail/
      - ./dms/config/:/tmp/docker-mailserver/
      - ./letsencrypt/acme.json:/etc/letsencrypt/acme.json:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - reverse-proxy
  
  reverse-proxy:
    image: traefik:v2.11
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      # From here on, it's the mailserver definition
      - --entryPoints.smtp.address=:25
      - --entryPoints.smtp-ssl.address=:465
      - --entryPoints.imap-ssl.address=:993
      - --entryPoints.sieve.address=:4190
      # Ending mailserver definition
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entryPoint=web
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.myresolver.acme.email=me@diegordonez.com
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
      # From here on, it's the mailserver definition
      - "25:25"
      - "465:465"
      - "993:993"
      - "4190:4190"
      - "10993:10993" # Is used here to avoid conflicts with Dovecot

      # Ending mailserver definition
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
  
  whoami:
    image: traefik/whoami
    container_name: test-services
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`mta.monojaus.com`)"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"